// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name_serv.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_name_5fserv_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_name_5fserv_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_name_5fserv_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_name_5fserv_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_name_5fserv_2eproto;
namespace nameserver {
class HeartBeatRequest;
struct HeartBeatRequestDefaultTypeInternal;
extern HeartBeatRequestDefaultTypeInternal _HeartBeatRequest_default_instance_;
class HeartBeatResponse;
struct HeartBeatResponseDefaultTypeInternal;
extern HeartBeatResponseDefaultTypeInternal _HeartBeatResponse_default_instance_;
}  // namespace nameserver
PROTOBUF_NAMESPACE_OPEN
template<> ::nameserver::HeartBeatRequest* Arena::CreateMaybeMessage<::nameserver::HeartBeatRequest>(Arena*);
template<> ::nameserver::HeartBeatResponse* Arena::CreateMaybeMessage<::nameserver::HeartBeatResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nameserver {

// ===================================================================

class HeartBeatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nameserver.HeartBeatRequest) */ {
 public:
  inline HeartBeatRequest() : HeartBeatRequest(nullptr) {}
  ~HeartBeatRequest() override;
  explicit PROTOBUF_CONSTEXPR HeartBeatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeatRequest(const HeartBeatRequest& from);
  HeartBeatRequest(HeartBeatRequest&& from) noexcept
    : HeartBeatRequest() {
    *this = ::std::move(from);
  }

  inline HeartBeatRequest& operator=(const HeartBeatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeatRequest& operator=(HeartBeatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeatRequest* internal_default_instance() {
    return reinterpret_cast<const HeartBeatRequest*>(
               &_HeartBeatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HeartBeatRequest& a, HeartBeatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeatRequest& from) {
    HeartBeatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nameserver.HeartBeatRequest";
  }
  protected:
  explicit HeartBeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChangeFilesFieldNumber = 3,
    kAddFieldNumber = 5,
    kNameFieldNumber = 1,
    kHostFieldNumber = 4,
    kHasChangeFieldNumber = 2,
  };
  // repeated string change_files = 3;
  int change_files_size() const;
  private:
  int _internal_change_files_size() const;
  public:
  void clear_change_files();
  const std::string& change_files(int index) const;
  std::string* mutable_change_files(int index);
  void set_change_files(int index, const std::string& value);
  void set_change_files(int index, std::string&& value);
  void set_change_files(int index, const char* value);
  void set_change_files(int index, const char* value, size_t size);
  std::string* add_change_files();
  void add_change_files(const std::string& value);
  void add_change_files(std::string&& value);
  void add_change_files(const char* value);
  void add_change_files(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& change_files() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_change_files();
  private:
  const std::string& _internal_change_files(int index) const;
  std::string* _internal_add_change_files();
  public:

  // repeated bool add = 5;
  int add_size() const;
  private:
  int _internal_add_size() const;
  public:
  void clear_add();
  private:
  bool _internal_add(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      _internal_add() const;
  void _internal_add_add(bool value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      _internal_mutable_add();
  public:
  bool add(int index) const;
  void set_add(int index, bool value);
  void add_add(bool value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      add() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      mutable_add();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string host = 4;
  void clear_host();
  const std::string& host() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_host(ArgT0&& arg0, ArgT... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* host);
  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(const std::string& value);
  std::string* _internal_mutable_host();
  public:

  // bool has_change = 2;
  void clear_has_change();
  bool has_change() const;
  void set_has_change(bool value);
  private:
  bool _internal_has_change() const;
  void _internal_set_has_change(bool value);
  public:

  // @@protoc_insertion_point(class_scope:nameserver.HeartBeatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> change_files_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool > add_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_;
    bool has_change_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_name_5fserv_2eproto;
};
// -------------------------------------------------------------------

class HeartBeatResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nameserver.HeartBeatResponse) */ {
 public:
  inline HeartBeatResponse() : HeartBeatResponse(nullptr) {}
  ~HeartBeatResponse() override;
  explicit PROTOBUF_CONSTEXPR HeartBeatResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeatResponse(const HeartBeatResponse& from);
  HeartBeatResponse(HeartBeatResponse&& from) noexcept
    : HeartBeatResponse() {
    *this = ::std::move(from);
  }

  inline HeartBeatResponse& operator=(const HeartBeatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeatResponse& operator=(HeartBeatResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeatResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeatResponse* internal_default_instance() {
    return reinterpret_cast<const HeartBeatResponse*>(
               &_HeartBeatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HeartBeatResponse& a, HeartBeatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeatResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeatResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeatResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeatResponse& from) {
    HeartBeatResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeatResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nameserver.HeartBeatResponse";
  }
  protected:
  explicit HeartBeatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:nameserver.HeartBeatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_name_5fserv_2eproto;
};
// ===================================================================

class NameService_Stub;

class NameService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline NameService() {};
 public:
  virtual ~NameService();

  typedef NameService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void HeartBeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::nameserver::HeartBeatRequest* request,
                       ::nameserver::HeartBeatResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(NameService);
};

class NameService_Stub : public NameService {
 public:
  NameService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  NameService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~NameService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements NameService ------------------------------------------

  void HeartBeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::nameserver::HeartBeatRequest* request,
                       ::nameserver::HeartBeatResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(NameService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HeartBeatRequest

// string name = 1;
inline void HeartBeatRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& HeartBeatRequest::name() const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HeartBeatRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.name)
}
inline std::string* HeartBeatRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:nameserver.HeartBeatRequest.name)
  return _s;
}
inline const std::string& HeartBeatRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void HeartBeatRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* HeartBeatRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* HeartBeatRequest::release_name() {
  // @@protoc_insertion_point(field_release:nameserver.HeartBeatRequest.name)
  return _impl_.name_.Release();
}
inline void HeartBeatRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nameserver.HeartBeatRequest.name)
}

// string host = 4;
inline void HeartBeatRequest::clear_host() {
  _impl_.host_.ClearToEmpty();
}
inline const std::string& HeartBeatRequest::host() const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatRequest.host)
  return _internal_host();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HeartBeatRequest::set_host(ArgT0&& arg0, ArgT... args) {
 
 _impl_.host_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.host)
}
inline std::string* HeartBeatRequest::mutable_host() {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:nameserver.HeartBeatRequest.host)
  return _s;
}
inline const std::string& HeartBeatRequest::_internal_host() const {
  return _impl_.host_.Get();
}
inline void HeartBeatRequest::_internal_set_host(const std::string& value) {
  
  _impl_.host_.Set(value, GetArenaForAllocation());
}
inline std::string* HeartBeatRequest::_internal_mutable_host() {
  
  return _impl_.host_.Mutable(GetArenaForAllocation());
}
inline std::string* HeartBeatRequest::release_host() {
  // @@protoc_insertion_point(field_release:nameserver.HeartBeatRequest.host)
  return _impl_.host_.Release();
}
inline void HeartBeatRequest::set_allocated_host(std::string* host) {
  if (host != nullptr) {
    
  } else {
    
  }
  _impl_.host_.SetAllocated(host, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:nameserver.HeartBeatRequest.host)
}

// bool has_change = 2;
inline void HeartBeatRequest::clear_has_change() {
  _impl_.has_change_ = false;
}
inline bool HeartBeatRequest::_internal_has_change() const {
  return _impl_.has_change_;
}
inline bool HeartBeatRequest::has_change() const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatRequest.has_change)
  return _internal_has_change();
}
inline void HeartBeatRequest::_internal_set_has_change(bool value) {
  
  _impl_.has_change_ = value;
}
inline void HeartBeatRequest::set_has_change(bool value) {
  _internal_set_has_change(value);
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.has_change)
}

// repeated string change_files = 3;
inline int HeartBeatRequest::_internal_change_files_size() const {
  return _impl_.change_files_.size();
}
inline int HeartBeatRequest::change_files_size() const {
  return _internal_change_files_size();
}
inline void HeartBeatRequest::clear_change_files() {
  _impl_.change_files_.Clear();
}
inline std::string* HeartBeatRequest::add_change_files() {
  std::string* _s = _internal_add_change_files();
  // @@protoc_insertion_point(field_add_mutable:nameserver.HeartBeatRequest.change_files)
  return _s;
}
inline const std::string& HeartBeatRequest::_internal_change_files(int index) const {
  return _impl_.change_files_.Get(index);
}
inline const std::string& HeartBeatRequest::change_files(int index) const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatRequest.change_files)
  return _internal_change_files(index);
}
inline std::string* HeartBeatRequest::mutable_change_files(int index) {
  // @@protoc_insertion_point(field_mutable:nameserver.HeartBeatRequest.change_files)
  return _impl_.change_files_.Mutable(index);
}
inline void HeartBeatRequest::set_change_files(int index, const std::string& value) {
  _impl_.change_files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::set_change_files(int index, std::string&& value) {
  _impl_.change_files_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::set_change_files(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.change_files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::set_change_files(int index, const char* value, size_t size) {
  _impl_.change_files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:nameserver.HeartBeatRequest.change_files)
}
inline std::string* HeartBeatRequest::_internal_add_change_files() {
  return _impl_.change_files_.Add();
}
inline void HeartBeatRequest::add_change_files(const std::string& value) {
  _impl_.change_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::add_change_files(std::string&& value) {
  _impl_.change_files_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::add_change_files(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.change_files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:nameserver.HeartBeatRequest.change_files)
}
inline void HeartBeatRequest::add_change_files(const char* value, size_t size) {
  _impl_.change_files_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:nameserver.HeartBeatRequest.change_files)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
HeartBeatRequest::change_files() const {
  // @@protoc_insertion_point(field_list:nameserver.HeartBeatRequest.change_files)
  return _impl_.change_files_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
HeartBeatRequest::mutable_change_files() {
  // @@protoc_insertion_point(field_mutable_list:nameserver.HeartBeatRequest.change_files)
  return &_impl_.change_files_;
}

// repeated bool add = 5;
inline int HeartBeatRequest::_internal_add_size() const {
  return _impl_.add_.size();
}
inline int HeartBeatRequest::add_size() const {
  return _internal_add_size();
}
inline void HeartBeatRequest::clear_add() {
  _impl_.add_.Clear();
}
inline bool HeartBeatRequest::_internal_add(int index) const {
  return _impl_.add_.Get(index);
}
inline bool HeartBeatRequest::add(int index) const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatRequest.add)
  return _internal_add(index);
}
inline void HeartBeatRequest::set_add(int index, bool value) {
  _impl_.add_.Set(index, value);
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatRequest.add)
}
inline void HeartBeatRequest::_internal_add_add(bool value) {
  _impl_.add_.Add(value);
}
inline void HeartBeatRequest::add_add(bool value) {
  _internal_add_add(value);
  // @@protoc_insertion_point(field_add:nameserver.HeartBeatRequest.add)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
HeartBeatRequest::_internal_add() const {
  return _impl_.add_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
HeartBeatRequest::add() const {
  // @@protoc_insertion_point(field_list:nameserver.HeartBeatRequest.add)
  return _internal_add();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
HeartBeatRequest::_internal_mutable_add() {
  return &_impl_.add_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
HeartBeatRequest::mutable_add() {
  // @@protoc_insertion_point(field_mutable_list:nameserver.HeartBeatRequest.add)
  return _internal_mutable_add();
}

// -------------------------------------------------------------------

// HeartBeatResponse

// bool success = 1;
inline void HeartBeatResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool HeartBeatResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool HeartBeatResponse::success() const {
  // @@protoc_insertion_point(field_get:nameserver.HeartBeatResponse.success)
  return _internal_success();
}
inline void HeartBeatResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void HeartBeatResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:nameserver.HeartBeatResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace nameserver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_name_5fserv_2eproto
